### ISSUE TITLE
Will Not Run Under Windows 7

### ISSUE THREAD

**Issue by vincentmaggard** [SotaJoe/EAS-Encoder#1]
Hi This Software is Not Runing Under Windows 7. I Am Willing To Work With You On This Issue.
Thank You For Time

**Comment by sasquelch** [comment]
I see what you mean - the windows form application is missing the .resx file.  It somehow didn't get checked in with the project.  However, the .dll library still compiles and works correctly.  I'll try to find a moment soon to get my local copy checked in with the missing file.  I used a Win7 machine to develop this project - so it will work once I get the missing file checked in.

Thanks for finding and reporting this issue!  Cheers!

**Comment by vincentmaggard** [comment]
It Was Not A Problem To Report It.
Please Let Me Know When You Have Updated It. 
Thank You

**Comment by sasquelch** [comment]
Ok - I've pushed the latest changes with the missing resx file included, and also changed the .NET version from 6 to 4.5.2 for better client support (at the moment, anyway.)  You should be set to pull the latest code and run.  Make sure to set your startup project to the tester application instead of the library file.  Cheers!

**Comment by vincentmaggard** [comment]
Thank You For The Infomation!
